version: '3.8'

services:
  php-app:
    build: .
    container_name: php_privilegios_app
    working_dir: /var/www/html
    volumes:
      - /home/fschner/Documentos/Codigos/privilegios:/var/www/html
    environment:
      - DB_HOST=seu_host_mysql_remoto
      - DB_PORT=3306
      - DB_NAME=seu_banco
      - DB_USER=seu_usuario
      - DB_PASS=sua_senha
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: nginx_php
    ports:
      - "8080:80"
    volumes:
      - /home/fschner/Documentos/Codigos/privilegios:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge